### ISSUE TITLE
Challenge Added to A2S_INFO

### ISSUE THREAD

**Issue by Crowdedlight** [dsyomichev/source-server-query#4]
It seems like steam is slowly rolling out a new version of the query where A2S_INFO also includes a challenge to avoid reflection attacks. https://steamcommunity.com/discussions/forum/14/2974028351344359625/ 

As such the INFO query does not work with the new version. (We are experiencing this on our server currently)

The documentation is updated to reflect the change: https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO 

Any possibilities to get this lib updated to support the change?

**Comment by Crowdedlight** [comment]
I fixed it for myself with a change to the challenge function. 

```
const challenge = async (address, port, code, timeout = 1000, payload = null) => {
  if (!address || typeof address != "string") return new Error("Missing/Invalid param 'address'");
  if (!port || typeof port != "number") return new Error("Missing/Invalid param 'port'");
  if (!code || typeof code != "string") return new Error("Missing/Invalid param 'code'");
  if (typeof timeout != "number") return new Error("Invalid Param 'timeout'");

  let buffer = null
  // check for payload, as INFO challenge requires that, otherwise send without payload
  if (payload != null && code == "T") {
    buffer = send(bp.pack("<isSi", [-1, code, "Source Engine Query", -1]), address, port, "A", timeout);
  } else {
    buffer = send(bp.pack("<isi", [-1, code, -1]), address, port, "A", timeout);
  }

  try {
    buffer = await buffer;
  } catch (err) {
    return typeof err == "string" ? new Error(err) : err;
  }
  return bp.unpack("<i", buffer)[0];
};
``` 

And then add the "payload" parameter and challenge code to the INFO function:
```
  let key = challenge(address, port, "T", timeout, "Source Engine Query");
  try {
    key = await key;
  } catch (err) {
    return typeof err == "string" ? new Error(err) : err;
  }

  let buffer = send(bp.pack("<isSi", [-1, "T", "Source Engine Query", key]), address, port, "I", timeout);
  try {
    buffer = await buffer;
  } catch (err) {
    return typeof err == "string" ? new Error(err) : err;
  }
  ```

**Comment by dsyomichev** [comment]
Hi, if you are willing, can you submit a pull request and I'll look it
over. I will be busy for the next couple of weeks but that should speed
things up.

**Comment by Crowdedlight** [comment]
Done. As the text in the PR says this is more a "duct-tape" PR that worked for my needs specifically. I have not validated or tested how well it works in cases where there is no challenge requested.

**Comment by dsyomichev** [comment]
HI, sorry for the really late response, but I finally update the package so
it SHOULD support the new challenge request. However I'm still trying to
find a server that's actually using this. If you could either send me an
address/port, or test the new commit on the github, it would be greatly
appreciated. Thank you for bringing this issue to my attention!

**Comment by TiBarification** [comment]
@dsyomichev , good package, but it doesn't work (failures some at challange part) then exits by timeout.

Try this ip `37.230.228.130` with port `27777`

**Comment by dsyomichev** [comment]
@TiBarification Thank you for the endpoint, I can finally test the challenge. I just pushed an update to NPM that should fix that issue. Going to close this now.

**Comment by Crowdedlight** [comment]
Hey sorry for no reply. Have been quite busy. Glad you got it working! Can go away from my local changes now ;-)
