### ISSUE TITLE
Server info query timeout when server is reachable

### ISSUE THREAD

**Issue by CyberSamurai0** [dsyomichev/source-server-query#9]
`info()` is throwing a response timeout for a server that is known to be reachable.
- Tried using different timeouts (1000ms, 5000ms, 10000ms), no change.
- Tried a different library to test for responsiveness, server responded to query very quickly.

**Comment by dsyomichev** [comment]
Could you add the hosts address and port? Can't really figure out what's going on otherwise. Thanks.

**Comment by CyberSamurai0** [comment]
@dsyomichev No problem, working with `208.103.169.109:27016`

**Comment by dsyomichev** [comment]
I can't seem to replicate the issue. Received a response containing the following:

```
{
  header: 'I',
  protocol: 17,
  name: 'Triangulum Roleplay',
  ...
  port: 27016,
  ...
  keywords: ' gm:starwarsrp gmws:248302805 gmc:rp ver:220310',
  gameid: 4000n
}
```

**Comment by CyberSamurai0** [comment]
Found the source of the problem, I was supplying the port as a string rather than a number.

**Comment by dsyomichev** [comment]
Yep, I was using strong comparison to compare the port when the packet is received so it would fail on the string. I fixed this in the latest npm release. Thanks for pointing it out.
